# Generated by Django 3.2.2 on 2021-10-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211005_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='upload',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
